### ISSUE TITLE
Define proxies for `PricesYahoo`

### ISSUE THREAD

**Issue by quant2008** [maread99/market_prices#128]
I run the following example:
```
from market_prices import PricesYahoo
prices = PricesYahoo("MSFT")  # prices for a single instrument, Microsoft
prices.get("5min", minutes=40)  # last 40 minutes of prices at 5 minute intervals
```
and got the following error:

TypeError                                 Traceback (most recent call last)
<ipython-input-8-f8ce55d96bdc> in <module>
      1 from market_prices import PricesYahoo
----> 2 prices = PricesYahoo("MSFT")  # prices for a single instrument, Microsoft
      3 prices.get("5min", minutes=40)  # last 40 minutes of prices at 5 minute intervals

e:\anaconda3\lib\site-packages\pydantic\decorator.cp38-win_amd64.pyd in pydantic.decorator.validate_arguments.validate.wrapper_function()

e:\anaconda3\lib\site-packages\pydantic\decorator.cp38-win_amd64.pyd in pydantic.decorator.ValidatedFunction.call()

e:\anaconda3\lib\site-packages\pydantic\decorator.cp38-win_amd64.pyd in pydantic.decorator.ValidatedFunction.execute()

e:\anaconda3\lib\site-packages\market_prices\prices\yahoo.py in __init__(self, symbols, calendars, lead_symbol, delays)
    348         self._cache_vol_bug_adj_start: None | tuple[pd.Timestamp, pd.Timestamp] = None
    349         self._set_daily_bi_limit()
--> 350         super().__init__(symbols, calendars, lead_symbol, delays)
    351 
    352     # Methods called via constructor

e:\anaconda3\lib\site-packages\market_prices\prices\base.py in __init__(self, symbols, calendars, lead_symbol, delays)
    440         self._set_pdata()
    441         self._trading_indexes_: dict[BI, pd.IntervalIndex]
--> 442         self._set_trading_indexes()
    443         self._indices_aligned_: dict[BI, pd.Series]
...
    603         # evaluate index as nano array

<__array_function__ internals> in concatenate(*args, **kwargs)

TypeError: concatenate() got an unexpected keyword argument 'dtype'

**Comment by maread99** [comment]
Hi @quant2008, I'm not able to recreate this.

Which version of `market_prices` are you using? The latest version is 0.9.10.

```python
>>> import market_prices
>>> market_prices.__version__
'0.9.10'
```

**Comment by quant2008** [comment]
It's 0.9.10.
I am in China, yahoo finance is blocked here. I use a vpn to access yahoo, so I guess I need to set proxy ip and port in your library, but I don't know how.

**Comment by maread99** [comment]
Could it be that you're using an old version of numpy, pre 1.20?

I suspect your issue would be resolved by upgrading numpy to the latest version (or indeed any version from 1.20).

**Comment by quant2008** [comment]
I upgrade my numpy, and now it gives the following error:

Traceback (most recent call last):
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\ProgramFiles\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\ProgramFiles\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "E:\ProgramFiles\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\myquant\venv_quant389\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "e:\myquant\venv_quant389\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v6/finance/quote/validate?lang=en-US&region=US&corsDomain=finance.yahoo.com&symbols=MSFT (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/mypyoptimize/py-smart-roster/test.py", line 2, in <module>
    prices = PricesYahoo("MSFT")  # prices for a single instrument, Microsoft
  File "pydantic\decorator.py", line 52, in pydantic.decorator.validate_arguments.validate.wrapper_function
    """
  File "pydantic\decorator.py", line 140, in pydantic.decorator.ValidatedFunction.call
    evaldict = evaldict or {}
  File "pydantic\decorator.py", line 203, in pydantic.decorator.ValidatedFunction.execute
    ba = sig.bind(*args, **kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\yahoo.py", line 322, in __init__
    self._ticker = yq.Ticker(
  File "e:\myquant\venv_quant389\lib\site-packages\yahooquery\ticker.py", line 94, in __init__
    self.validation
  File "e:\myquant\venv_quant389\lib\site-packages\yahooquery\base.py", line 1009, in validation
    data = self._chunk_symbols("validation")
  File "e:\myquant\venv_quant389\lib\site-packages\yahooquery\base.py", line 991, in _chunk_symbols
    data = self._get_data(key, params, disable=True, **kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\yahooquery\base.py", line 1078, in _get_data
    data = self._async_requests(response_field, urls, params, **kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\yahooquery\base.py", line 1162, in _async_requests
    response = future.result()
  File "E:\ProgramFiles\Python\Python38\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "E:\ProgramFiles\Python\Python38\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "E:\ProgramFiles\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\yahooquery\utils\__init__.py", line 48, in send
    return super(TimeoutHTTPAdapter, self).send(request, **kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v6/finance/quote/validate?lang=en-US&region=US&corsDomain=finance.yahoo.com&symbols=MSFT (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

**Comment by maread99** [comment]
This is now a connection issue, probably due to the access issues you mentioned.

The default `PricesYahoo` class uses the [yahooquery](https://github.com/dpguthrie/yahooquery) library to get the raw price data from yahoo. `yahooquery` does provide for [defining proxies](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#proxies) in a similar way to `yfinance`, however `PricesYahoo` currently does not offer a way to pass these through to `yahooquery` (I've renamed this issue with the intention of facilitating this in the future).

In the meantime you could try setting the  `HTTP_PROXY` and `HTTPS_PROXY` environmental variables as suggested on the [yahooquery doc](https://yahooquery.dpguthrie.com/guide/keyword_arguments/#proxies), or implement a local hack to pass through the proxy address.

Let me know how you get on.

**Comment by quant2008** [comment]
In windows command line，I set：
set HTTP_PROXY=http://127.0.0.1:7890 
set HTTPS_PROXY=https://127.0.0.1:7890 

Then I execute the programm, this time I get following error:
Traceback (most recent call last):
  File "e:/mypyoptimize/py-smart-roster/test.py", line 2, in <module>
    prices = PricesYahoo("MSFT")  # prices for a single instrument, Microsoft
  File "pydantic\decorator.py", line 52, in pydantic.decorator.validate_arguments.validate.wrapper_function
    """
  File "pydantic\decorator.py", line 140, in pydantic.decorator.ValidatedFunction.call
    evaldict = evaldict or {}
  File "pydantic\decorator.py", line 203, in pydantic.decorator.ValidatedFunction.execute
    ba = sig.bind(*args, **kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\yahoo.py", line 338, in __init__
    self._set_yahoo_exchange_name()
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\yahoo.py", line 357, in _set_yahoo_exchange_name
    d[s] = self._ticker.quotes[s]["fullExchangeName"]
TypeError: list indices must be integers or slices, not str

**Comment by maread99** [comment]
Can you get prices from `yahooquery` setting the proxy as you have above? For example with:

```python
import yahooquery as yq
ticker = yq.Ticker("MSFT")
ticker.history(start="2022-12-01")
```

**Comment by quant2008** [comment]
I modify the set as follows

```
set HTTP_PROXY=http://127.0.0.1:7890
set HTTPS_PROXY=http://127.0.0.1:7890
```

Then the following works.
```
import yahooquery as yq
ticker = yq.Ticker("MSFT")
ticker.history(start="2022-12-01")
```

and the following also works.
```
from market_prices import PricesYahoo
prices = PricesYahoo("MSFT")  # prices for a single instrument, Microsoft
print(prices.get("1D", start="2022-02-15", months=3) )
```

But the following doesn't work.
```
from market_prices import PricesYahoo
prices = PricesYahoo("MSFT")  # prices for a single instrument, Microsoft
print(prices.get("5min", minutes=40)) 
```
Here is the error. I guess is it related to timezone?

Traceback (most recent call last):
  File "e:/mypyoptimize/py-smart-roster/test.py", line 3, in <module>
    print(prices.get("5min", minutes=40))
  File "pydantic\decorator.py", line 52, in pydantic.decorator.validate_arguments.validate.wrapper_function
    """
  File "pydantic\decorator.py", line 140, in pydantic.decorator.ValidatedFunction.call
    evaldict = evaldict or {}
  File "pydantic\decorator.py", line 203, in pydantic.decorator.ValidatedFunction.execute
    ba = sig.bind(*args, **kwargs)
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\base.py", line 3352, in get
    table = self._get_table_intraday()
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\base.py", line 1843, in _get_table_intraday
    df_bi, bi = self._get_bi_table_intraday()
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\base.py", line 1803, in _get_bi_table_intraday
    table = self._get_bi_table(bi, (start, end))
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\base.py", line 1752, in _get_bi_table
    table = self._pdata[bi].get_table(daterange)
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\data.py", line 686, in get_table
    self._extend_table(daterange)
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\data.py", line 637, in _extend_table
    req_dates, dfs = self._request_data(daterange)
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\data.py", line 546, in _request_data
    df = self._request_data_func(self.bi, rd[0], rd[1])
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\yahoo.py", line 1099, in _request_data
    prices = self._request_yahoo(interval=interval, start=start, end=end_)
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\yahoo.py", line 761, in _request_yahoo
    raise_error()
  File "e:\myquant\venv_quant389\lib\site-packages\market_prices\prices\yahoo.py", line 756, in raise_error
    raise errors.PricesUnavailableFromSourceError(params, prices)
market_prices.errors.PricesUnavailableFromSourceError: Prices unavailable from source for parameters: {'interval': '5m', 'start': Timestamp('2022-12-30 20:20:00+0000', tz='UTC'), 'end': Timestamp('2022-12-30 21:00:00+0000', tz='UTC')}.

**Comment by maread99** [comment]
Good to see you've managed to get it working via the proxy.

As for the `PricesUnavailableFromSourceError`, it's not immediately clear to me why this raised. It shouldn't be related to the timezone - the request goes to yahoo in terms of UTC and the `start` and `end` timestamps shown in the error message are as required. I've just run the same request locally and I get back the expected prices.

Can you try it again? If you get the same error back then could you let me know the time you made the request (UTC).

Also, if you want to have a play around with it with different symbols and parameters (maybe work through some of the [tutorials](https://github.com/maread99/market_prices/blob/master/docs/tutorials_docs.md)) and let me know any requests that are raising unexpected errors.

**Comment by maread99** [comment]
From 0.10 you can define a proxy by passing the `proxies` kwarg to `PricesYahoo`:

```
proxies
    Make requests for price data via a proxy.

    Pass as a dictionary mapping URL schemes to the proxy URL, for
    example:
        proxies = {
            'http': 'http://10.10.1.10:3128',
            'https': 'http://10.10.1.10:1080',
        }

    Value is passed through to the 'proxies' kwarg of
    `yahooquery.Ticker`.
```
