### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by shortland** [maread99/market_prices#220]
```
❯ /usr/bin/python3
Python 3.9.6 (default, May  7 2023, 23:32:45)
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from market_prices import PricesYahoo
>>> prices = PricesYahoo("MSFT")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ilankleiman/Library/Python/3.9/lib/python/site-packages/valimp/valimp.py", line 935, in wrapped_f
    return f(**new_as_kwargs)
  File "/Users/ilankleiman/Library/Python/3.9/lib/python/site-packages/market_prices/prices/yahoo.py", line 353, in __init__
    calendars = self._ascertain_calendars(calendars)
  File "/Users/ilankleiman/Library/Python/3.9/lib/python/site-packages/market_prices/prices/yahoo.py", line 389, in _ascertain_calendars
    exchange = self._yahoo_exchange_name[s]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/Users/ilankleiman/Library/Python/3.9/lib/python/site-packages/market_prices/prices/yahoo.py", line 369, in _yahoo_exchange_name
    d[s] = self._ticker.price[s]["exchangeName"]
TypeError: string indices must be integers
```

latest release, 0.11

**Comment by shortland** [comment]
#201 - works with python3.11; 3.9 support is no more 😄

**Comment by maread99** [comment]
Hi @shortland, thanks for the report.

This looks related to the Yahoo API which occasionally fails to return some endpoints. Seems to be back up now - it's working fine for me with 3.9.

Given the nature of the error, it should raise on both Python 3.9 and 3.11. It might have been that the API endpoint was back up when you tried on 3.11.

Let me know if you're still getting the error.

Cheers

**Comment by shortland** [comment]
I tried both 3.9.6 and 3.11.6 at the same time last night & now - with 3.9.6 giving me the error & 3.11.6 working fine both times. Seems like it's possibly an incompatibility in some dependency

**Comment by shortland** [comment]
3.9 is using the v10 api endpoint, while 3.11 is using the v6 endpoint:

turns out I needed to update the `yahooquery` package

<img width="1458" alt="Screenshot 2023-10-14 at 4 04 14 PM" src="https://github.com/maread99/market_prices/assets/8150093/dcc809b8-9b4a-4dec-ad44-40449bd90211">
